#!/bin/bash

usage() {
    echo "Usage: start_ethminer [-d delay] [-s] [-t] [-u]"
    exit 1
}

# Exit if miner already running or miner disabled
[ -x /usr/local/bin/check_miner ] && {
    /usr/local/bin/check_miner -q
    [ $? -gt 0 ] && {
        exit 1
    }
}

USE_POOL=nanopool
# ETHW settings for Nanopool
# export SSL_NOVERIFY=1
WWAL="0x3032Ed2453E4E542c543E2c70270b3b879B5A7Be"
WPOOL="ethw-us-west1.nanopool.org:15555"
XPOOL="ethw-us-east1.nanopool.org:15555"

# USE_POOL=ethermine
# Ledger Nano S ETH address
# EWAL="0x765972c4E777096CF94AEE2432a81B9510DfE6e4"
# Exodus Wallet ETH address
EWAL="0x3032Ed2453E4E542c543E2c70270b3b879B5A7Be"
EPOOL="us2.ethermine.org:5555"
FPOOL="us1.ethermine.org:5555"

# USE_POOL=etcethermine
# Exodus Wallet ETC address
CWAL="0x00eaD16d02035D3eF10fE2c4Daa002b213762Ac0"
CPOOL="us1-etc.ethermine.org:5555"

LOG="/var/run/miner.output"
USER=`id -u -n`
GRP=`id -g -n`
WORKER=`hostname`
#
# Use sequential DAG load if miner crashes during parallel load
# 0=parallel, 1=sequential
MODE="1"

[ -f ~/.nominer ] && exit 1

sudo touch $LOG
sudo chown ${USER}:${GRP} $LOG
delay=0
silent=
teelog=
while getopts d:stu flag; do
    case $flag in
        d)
            delay="$OPTARG"
            ;;
        s)
            silent=1
            ;;
        t)
            teelog=1
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

while [ $delay -gt 0 ]
do
    delay=`expr $delay - 1`
    [ "$silent" ] || echo -e -n "Starting miner in $delay seconds  \r"
    sleep 1
done

case "${USE_POOL}" in
  ethermine)
    if [ "$teelog" ]
    then
      sudo /usr/local/bin/ethminer \
        --dag-load-mode ${MODE} \
        --HWMON 1 \
        --opencl \
        --cl-nobin \
        --cl-noexit \
        --farm-recheck 2000 \
        --report-hashrate \
        -P stratum+ssl://${EWAL}.${WORKER}@${EPOOL} \
        -P stratum+ssl://${EWAL}.${WORKER}@${FPOOL} \
        2>&1 | /usr/bin/tee -a ${LOG}
    else
      sudo /usr/local/bin/ethminer \
        --dag-load-mode ${MODE} \
        --HWMON 1 \
        --opencl \
        --cl-nobin \
        --cl-noexit \
        --farm-recheck 2000 \
        --report-hashrate \
        -P stratum+ssl://${EWAL}.${WORKER}@${EPOOL} \
        -P stratum+ssl://${EWAL}.${WORKER}@${FPOOL} \
        > ${LOG} 2>&1
    fi
    ;;
  etcethermine)
    if [ "$teelog" ]
    then
      sudo /usr/local/bin/ethminer \
        --dag-load-mode ${MODE} \
        --HWMON 1 \
        --opencl \
        --cl-nobin \
        --cl-noexit \
        --farm-recheck 2000 \
        --report-hashrate \
        -P stratum+ssl://${CWAL}.${WORKER}@${CPOOL} \
        2>&1 | /usr/bin/tee -a ${LOG}
    else
      sudo /usr/local/bin/ethminer \
        --dag-load-mode ${MODE} \
        --HWMON 1 \
        --opencl \
        --cl-nobin \
        --cl-noexit \
        --farm-recheck 2000 \
        --report-hashrate \
        -P stratum+ssl://${CWAL}.${WORKER}@${CPOOL} \
        > ${LOG} 2>&1
    fi
    ;;
  nanopool)
    if [ "$teelog" ]
    then
      sudo /usr/local/bin/ethminer \
        --dag-load-mode ${MODE} \
        --HWMON 1 \
        --opencl \
        --cl-nobin \
        --cl-noexit \
        --farm-recheck 2000 \
        --report-hashrate \
        -P stratum+tcp://${WWAL}%2e${WORKER}%2fronaldrecord@gmail.com@${WPOOL} \
        -P stratum+tcp://${WWAL}%2e${WORKER}%2fronaldrecord@gmail.com@${XPOOL} \
        2>&1 | /usr/bin/tee -a ${LOG}
    else
      sudo /usr/local/bin/ethminer \
        --dag-load-mode ${MODE} \
        --HWMON 1 \
        --opencl \
        --cl-nobin \
        --cl-noexit \
        --farm-recheck 2000 \
        --report-hashrate \
        -P stratum+tcp://${WWAL}%2e${WORKER}%2fronaldrecord@gmail.com@${WPOOL} \
        -P stratum+tcp://${WWAL}%2e${WORKER}%2fronaldrecord@gmail.com@${XPOOL} \
        > ${LOG} 2>&1
    fi
    ;;
  *)
    echo "Unknown/unsupported Pool: ${USE_POOL}"
    ;;
esac
